### ISSUE TITLE
Queue shows first layer time instead of full print time

### ISSUE THREAD

**Issue by TrisDooley** [gavatron77/PrintQueueV3#1]
> s.contains("(normal mode)"))

returns true for 
> ; estimated first layer printing time (normal mode) = 28s

in 
> AddToQueue.java: line 24

and causes the time displayed to the queue to be the first layer instead of entire print time. This only applies to Prusaslicer 2.6 and up, when this line was added to the output.

**Comment by gavatron77** [comment]
Well that's awkward. I'll fix that in a bit
